
# Form:
#  {{ option name }} = {{ default value }}

# MusicDir is where your music is kept. Environment variables and tilde "~" can be used.
MusicDir = "$HOME/Music"

# LyricsDir is where your lyrics are kept. Environment variables and tilde "~" can be used.
LyricsDir = "$HOME/Music"

# MPD section.
[MPD]

# Connection can be "unix" or "tcp" depending on how you configured mpd.
Connection = "tcp"

# Address is path to unix socket or tcp "host:port". Environment variables and tilde "~" can be used.
Address = "localhost:6600"

# Password is the password set up in MPD. An empty string is no password.
Password = ""
