name: Go
on:
  push:
  pull_request:
    types: [opened, reopened]
jobs:
  go-unix:
    strategy:
      matrix:
        os-unix: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os-unix }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Check Format
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go install mvdan.cc/gofumpt@latest
          make checkfmt
      - name: Test
        run: make test
      - name: Build
        run: make build
